swagger: "2.0"
info:
  description: "This is a project about an API REST of products."
  version: "1.0.0"
  title: "Swagger Products"
  contact:
    email: "manuel.sanchez0394@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8031"
basePath: "/v1"
tags:
- name: "product"
  description: "Resources about products"
schemes:
- "http"
paths:
  /products/{productId}:
    get:
      tags:
      - "product"
      summary: "Find product by ID"
      description: "Returns a product"
      operationId: "getProductById"
      produces:
      - "application/json"
      parameters:
      - name: "productId"
        in: "path"
        description: "ID of product"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Product"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Product not found"
    put:
      tags:
      - "product"
      summary: "Updates a product"
      description: ""
      operationId: "updateProductById"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "productId"
        in: "path"
        description: "ID of product"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/Product"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Product not found"
        "405":
          description: "Validation exception"
definitions:
  Product:
    type: "object"
    required:
    - "description"
    - "model"
    properties:
      id:
        type: "string"
        maxLength: 10
        minLength: 10
        readOnly: true
      name:
        type: "string"
        maxLength: 20
        readOnly: true
      description:
        type: "string"
        maxLength: 200
      price:
        type: "number"
        multipleOf: 0.01
        readOnly: true
      model:
        type: "string"
        maxLength: 10